spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/member?useSSL=false&serverTimezone=Asia/Seoul}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
